### PR TITLE
Improvements 1.16 v2

### PR DESCRIPTION
**Pull request by 12tbuchman**
Various improvements to badger-amcl

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13)

### CODE REVIEW

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 7 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13)* status: 7 of 17 files reviewed, 4 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[CMakeLists.txt, line 77 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3Ncb_9pCj4FEM3ARw:-ME3Ncba8pD6p-CRO8VW:b-msidzu) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/CMakeLists.txt#L77)):*
> ```CMake
> )
> 
> add_executable(badger_amcl_exe
> ```

It is unusual to add `_exe` to the executable. I suggest naming it `badger_amcl_node` if you need to distinguish it from the library. Alternatively, leave it the same name as before, and use this technique to resolve the issue of both targets having the same cmake name:
https://gist.github.com/jlgerber/eafc4ee2b9954e27dd2bb009496b1b03
___
*[CMakeLists.txt, line 87 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3OVQOEBBhRe7ptSsC:-ME3OVQOEBBhRe7ptSsD:b-1z68jf) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/CMakeLists.txt#L87)):*
> ```CMake
> 
> if(CATKIN_ENABLE_TESTING)
>     catkin_add_gtest(TestBadgerAmcl test/test_badger_amcl.cpp)
> ```

I'm not sure about the camel case here. I would think it would be better to be `test_badger_amcl`, or if this should be came case, `TestBadgerAMCL`
___
*[include/amcl/node/node.h, line 124 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3OmER3cvRhfCb0J6b:-ME3OmER3cvRhfCb0J6c:b-5grw79) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/node/node.h#L124)):*
> ```objc
>   YAML::Node loadYamlFromFile();
>   bool getLatestTf(tf2::Transform* latest_tf);
>   void getLatestAmclPose(tf2::Transform latest_tf, geometry_msgs::PoseWithCovarianceStamped* latest_amcl_pose);
> ```

I'm not crazy about this name. I would either prefer `getLatestPose` (we are in AMCL, so the AMCL seems redundant), or pick a specific adjective describing the nature of this pose that is not `AMCL`.
___
*[include/amcl/pf/particle_filter.h, line 103 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3PEGA9Fl-DH_yvY-j:-ME3PEGA9Fl-DH_yvY-k:b-phukuy) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/pf/particle_filter.h#L103)):*
> ```objc
> 
>   // Initialize the filter using a guassian to generate initial poses
>   void initWithGaussian(const Eigen::Vector3d& mean, const Eigen::Matrix3d& cov);
> ```

I suggest ditching `WithGaussian` and overload the name `init` with this method and the method below. Then in the documentation, specify what the arguments mean for the 2 ways to `init`
___
*[include/amcl/pf/pdf_gaussian.h, line 36 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3Pa9RCuBWcBDVvCqf:-ME3Pa9RCuBWcBDVvCqg:b-52witd) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/pf/pdf_gaussian.h#L36)):*
> ```objc
>   // Create a gaussian pdf
>   PDFGaussian(const Eigen::Vector3d& x, const Eigen::Matrix3d& cx);
>   // Constructor used to seed random for testing
> ```

FYI, I think tests should be repeatable, and you should always seed them the same each time. I haven't checked yet how thi sis used, but please make sure you always seed it the same way, as we don't want test outcomes to be unpredictable.

**Comment by c-andy-martin** [comment]
___
*[test/test_badger_amcl.cpp, line 172 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3j4DU-M6AYTGdy5XL:-ME3j4DU-M6AYTGdy5XM:b-qj68fx) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L172)):*
> ```cpp
> {
>   testing::InitGoogleTest(&argc, argv);
>   ros::init(argc, argv, "BadgerTester");
> ```

The name "BadgerTester"...maybe it should be "BadgerAMCLTest"?

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13)* status: all files reviewed, 9 unresolved discussions (waiting on @12tbuchman)

___
*[src/amcl/pf/pdf_gaussian.cpp, line 49 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3iBH82Q5R3YhvzdxQ:-ME3iBH82Q5R3YhvzdxR:b-gqdmbl) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/src/amcl/pf/pdf_gaussian.cpp#L49)):*
> ```cpp
> PDFGaussian::PDFGaussian(const Eigen::Vector3d& x, const Eigen::Matrix3d& cx, int seed) : PDFGaussian(x, cx)
> {
>   srand(seed);
> ```

Seems like this should be `srand48`.
___
*[test/test_badger_amcl.cpp, line 31 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3iYVe0BPhE9-IszCP:-ME3iYVe0BPhE9-IszCQ:bxcgtn0) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L31)):*
> ```cpp
> TEST(TestBadgerAmcl, testPdfGaussian)
> {
>   // test 1
> ```

This comment should describe what it is you are trying to test.
___
*[test/test_badger_amcl.cpp, line 37 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3iiWf6YopzEuKYPI3:-ME3iiWf6YopzEuKYPI4:bgszvq5) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L37)):*
> ```cpp
>   badger_amcl::PDFGaussian pdf_gaussian(x, cx);
>   Eigen::Vector3d sample = pdf_gaussian.sample();
>   EXPECT_DOUBLE_EQ(sample[0], 0.26562654174915334);
> ```

Are you just checking that the pseudo random number generator is producing the number you expect here?
___
*[test/test_badger_amcl.cpp, line 40 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3ia1V8ti-52zNtCyG:-ME3ia1V8ti-52zNtCyH:bqujbyh) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L40)):*
> ```cpp
>   EXPECT_DOUBLE_EQ(sample[1], 0.97172090090793528);
>   EXPECT_DOUBLE_EQ(sample[2], -1.5856194295513539);
>   // test 2
> ```

Here too

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13)* status: all files reviewed, 9 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[CMakeLists.txt, line 87 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3OVQOEBBhRe7ptSsC:-ME44p8s-MTxe4IgYh0e:b-qdt44h) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/CMakeLists.txt#L87)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not sure about the camel case here. I would think it would be better to be `test_badger_amcl`, or if this should be came case, `TestBadgerAMCL`
</blockquote></details>

i got the naming convention from http://wiki.ros.org/gtest#Test_naming_conventions
___
*[include/amcl/pf/particle_filter.h, line 103 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3PEGA9Fl-DH_yvY-j:-ME47tSqCSdlzD_UlFzY:bauj8oy) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/pf/particle_filter.h#L103)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I suggest ditching `WithGaussian` and overload the name `init` with this method and the method below. Then in the documentation, specify what the arguments mean for the 2 ways to `init`
</blockquote></details>

To me, overriding a function usually implies a polymorphism that doesnt exist here. What is the benefit of overriding the function if we are not doing so to allow polymorphism? Instead that forces the code to be commented to explain what is already easily understood through a more detailed name
___
*[include/amcl/pf/pdf_gaussian.h, line 36 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3Pa9RCuBWcBDVvCqf:-ME49-Z82jW5vPSuzZPk:b-dwfvk) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/pf/pdf_gaussian.h#L36)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

FYI, I think tests should be repeatable, and you should always seed them the same each time. I haven't checked yet how thi sis used, but please make sure you always seed it the same way, as we don't want test outcomes to be unpredictable.
</blockquote></details>

Yes, it is given the same seed each time.
___
*[test/test_badger_amcl.cpp, line 37 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3iiWf6YopzEuKYPI3:-ME4BSsj5FLFMbFVfOcJ:bh2ft6x) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L37)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Are you just checking that the pseudo random number generator is producing the number you expect here?
</blockquote></details>

If by the pseudo random number generator you mean the sample function, yes. if you mean the computer's generator, no.. there is some manipulation beyond the call to drand48 based on the model we are sampling from. It is a simple test but not entirely trivial.

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13)* status: 1 of 17 files reviewed, 9 unresolved discussions (waiting on @c-andy-martin)

___
*[CMakeLists.txt, line 77 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3Ncb_9pCj4FEM3ARw:-ME8V1x1BVRWZUiNPJXU:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/CMakeLists.txt#L77)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It is unusual to add `_exe` to the executable. I suggest naming it `badger_amcl_node` if you need to distinguish it from the library. Alternatively, leave it the same name as before, and use this technique to resolve the issue of both targets having the same cmake name:
https://gist.github.com/jlgerber/eafc4ee2b9954e27dd2bb009496b1b03
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 124 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3OmER3cvRhfCb0J6b:-ME8YfkR0cEkeGwfaCl9:bbvrs80) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/node/node.h#L124)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not crazy about this name. I would either prefer `getLatestPose` (we are in AMCL, so the AMCL seems redundant), or pick a specific adjective describing the nature of this pose that is not `AMCL`.
</blockquote></details>

This function is based on a variable called `latest_amcl_pose_` and related mutex `latest_amcl_pose_mutex_`, hence I was keeping the naming convention the same. I agree though that `amcl doesnt` need to be a part of the name so i have removed that in both variables and the function names.
___
*[src/amcl/pf/pdf_gaussian.cpp, line 49 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3iBH82Q5R3YhvzdxQ:-ME8jgtt732xsWQpFBaW:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/src/amcl/pf/pdf_gaussian.cpp#L49)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Seems like this should be `srand48`.
</blockquote></details>

Done.
___
*[test/test_badger_amcl.cpp, line 31 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3iYVe0BPhE9-IszCP:-ME8jiGk5ylktwx5y_FR:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L31)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This comment should describe what it is you are trying to test.
</blockquote></details>

Done.
___
*[test/test_badger_amcl.cpp, line 40 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3ia1V8ti-52zNtCyG:-ME8jiZ-93yuGRKQ2YbY:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L40)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.
___
*[test/test_badger_amcl.cpp, line 172 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3j4DU-M6AYTGdy5XL:-ME8kR2tAlmKZJlgdtwO:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/test/test_badger_amcl.cpp#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

The name "BadgerTester"...maybe it should be "BadgerAMCLTest"?
</blockquote></details>

Done.

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[include/amcl/pf/particle_filter.h, line 103 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/13#-ME3PEGA9Fl-DH_yvY-j:-MEO2qTQ-TLyAim41Yn4:b-jjd02t) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/bdbdaf0c1e75922d903d684898227237fbd35062/include/amcl/pf/particle_filter.h#L103)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

To me, overriding a function usually implies a polymorphism that doesnt exist here. What is the benefit of overriding the function if we are not doing so to allow polymorphism? Instead that forces the code to be commented to explain what is already easily understood through a more detailed name
</blockquote></details>

While I don't completely agree, this is just a nit and can really go either way. I think you are overloading the meaning here, there are two ways to init. But this is OK, as you point out, it makes the code more readable.

**Pull request merged**
