### PR TITLE
Improve naming

### PR DESCRIPTION
**Pull request by 12tbuchman**
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)

### CODE REVIEW

**Review by coxep — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-:-MJbpMzY5I9LcC26NPNt:bb6ywmx)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @coxep)

**Review by coxep — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by c-andy-martin** [comment]
LGTM, except for "octmap" in the commit summary which should be "octomap"

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: all files reviewed, 3 unresolved discussions (waiting on @12tbuchman)

___
*[src/amcl/node/node.cpp, line 132 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKFzzV14HfG5WBdXe_v:-MKFzzV14HfG5WBdXe_w:b-bvwds6) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node.cpp#L132)):*
> ```cpp
>   transform_tolerance_.fromSec(transform_tolerance_val);
> 
>   initial_pose_sub_ = nh_.subscribe("/initialpose", 2, &Node::initialPoseReceived, this);
> ```

I would rather handle this in the launch file with a remap from "initialpose" to "/initialpose"
___
*[src/amcl/node/node.cpp, line 154 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKFzug7E4BpY5E5rBzp:-MKFzug8CXGiyujx769o:bsgtzdq) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node.cpp#L154)):*
> ```cpp
>   if(odom_integrator_enabled_);
>   {
>     std::string odom_integrator_topic = "/odom";
> ```

Hmm. I would much rather handle this with a "remap" in the launch file of the "odom" in the name space to "/odom"
___
*[src/amcl/node/node_3d.cpp, line 110 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKG-ATKCw5jPRp3QmXH:-MKG-ATKCw5jPRp3QmXI:bpaiuxw) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node_3d.cpp#L110)):*
> ```cpp
>   first_octomap_received_ = false;
>   occupancy_bounds_received_ = false;
>   octo_map_sub_ = nh_.subscribe("octomap", 1, &Node3D::octoMapMsgReceived, this);
> ```

why did you make this change? "octomap" is the full octomap with probabilities. I think we only need the "octomap_binary" which is occupancy only information.

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: all files reviewed, 3 unresolved discussions (waiting on @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 132 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKFzzV14HfG5WBdXe_v:-MKG0-427Dzrf6XkcvTL:b-t77xc3) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node.cpp#L132)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would rather handle this in the launch file with a remap from "initialpose" to "/initialpose"
</blockquote></details>

agreed
___
*[src/amcl/node/node.cpp, line 154 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKFzug7E4BpY5E5rBzp:-MKG00oj3TSOf2vnyH4j:b-t77xc3) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node.cpp#L154)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Hmm. I would much rather handle this with a "remap" in the launch file of the "odom" in the name space to "/odom"
</blockquote></details>

agreed
___
*[src/amcl/node/node_3d.cpp, line 110 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKG-ATKCw5jPRp3QmXH:-MKG04BS9aUmBmlAOegL:bmcvwep) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node_3d.cpp#L110)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

why did you make this change? "octomap" is the full octomap with probabilities. I think we only need the "octomap_binary" which is occupancy only information.
</blockquote></details>

its being remapped in the launch file now

**Comment by c-andy-martin** [comment]
___
*[src/amcl/node/node_3d.cpp, line 110 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKG-ATKCw5jPRp3QmXH:-MKG1LwgCQpDgxvk_M7Z:b-avm7hl) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node_3d.cpp#L110)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

its being remapped in the launch file now
</blockquote></details>

OK, that's fine, esp since I see now from looking at the code that we will handle either kind of octree. This is OK

**Comment by c-andy-martin** [comment]
___
*[src/amcl/node/node.cpp, line 284 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKGAZ9UA8c1xo6d2hbE:-MKGAZ9UA8c1xo6d2hbF:b88u0eh) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node.cpp#L284)):*
> ```cpp
>   saved_pose_filepath_ = config.saved_pose_filepath;
>   initial_pose_sub_ = nh_.subscribe("initialpose", 2, &Node::initialPoseReceived, this);
>   publish_transform_timer_ = nh_.createTimer(transform_publish_period_, std::bind(&Node::publishTransform, this,
> ```

I think you still need to re-create the timer, as the transform_publish_period_ is dynamic

**Review by c-andy-martin — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: all files reviewed, 1 unresolved discussion (waiting on @12tbuchman)

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 284 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKGAZ9UA8c1xo6d2hbE:-MKGdFa943MFcTLPCkJd:b-k73z76) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/a4760d7b879c735bfcc230929c3ef5be7c99f4e9/src/amcl/node/node.cpp#L284)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think you still need to re-create the timer, as the transform_publish_period_ is dynamic
</blockquote></details>

thanks

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: all files reviewed, 4 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 283 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKLDpjw3-piIQRC9OKU:-MKLDpjx0qVNNlFzhE0m:b-psu4rn) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/d26ece4c9cc36e2fbcef6b7ea1310ea7ed585852/src/amcl/node/node.cpp#L283)):*
> ```cpp
>   save_pose_ = config.save_pose;
>   saved_pose_filepath_ = config.saved_pose_filepath;
>   publish_transform_timer_.stop();
> ```

you could instead just change the period of the timer with `setPeriod` instead of stopping and recreating.
___
*[src/amcl/node/node.cpp, line 287 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKLDjza5x6trWz8Sm9T:-MKLDjza5x6trWz8Sm9U:bszhmjp) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/d26ece4c9cc36e2fbcef6b7ea1310ea7ed585852/src/amcl/node/node.cpp#L287)):*
> ```cpp
>                                                                std::bind(&Node::publishTransform, this,
>                                                                          std::placeholders::_1));
>   publish_transform_spinner_.start();
> ```

This new line of code seems unnecessary as the spinner will already have been started.
___
*[src/amcl/node/node_2d.cpp, line 191 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKLE1eN88x_B2u2oH21:-MKLE1eN88x_B2u2oH22:b-59ujjb) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/d26ece4c9cc36e2fbcef6b7ea1310ea7ed585852/src/amcl/node/node_2d.cpp#L191)):*
> ```cpp
>   scanner_.setMapFactors(off_map_factor_, non_free_space_factor_, non_free_space_radius_);
> 
>   scan_sub_.release();
> ```

I'm not sure why you made a change here. Overwritting the pointer is going to have nearly an identical effect. Was this change necessary?

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 283 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKLDpjw3-piIQRC9OKU:-MKLXdGpCzm9jM0aTrCk:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/d26ece4c9cc36e2fbcef6b7ea1310ea7ed585852/src/amcl/node/node.cpp#L283)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

you could instead just change the period of the timer with `setPeriod` instead of stopping and recreating.
</blockquote></details>

Done.
___
*[src/amcl/node/node.cpp, line 287 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKLDjza5x6trWz8Sm9T:-MKLXf3BD2esnA_lpnIa:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/d26ece4c9cc36e2fbcef6b7ea1310ea7ed585852/src/amcl/node/node.cpp#L287)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This new line of code seems unnecessary as the spinner will already have been started.
</blockquote></details>

Done.
___
*[src/amcl/node/node_2d.cpp, line 191 at r4](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-MKLE1eN88x_B2u2oH21:-MKLQ_4y6mkAFHoGRyMO:bz2n06r) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/d26ece4c9cc36e2fbcef6b7ea1310ea7ed585852/src/amcl/node/node_2d.cpp#L191)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm not sure why you made a change here. Overwritting the pointer is going to have nearly an identical effect. Was this change necessary?
</blockquote></details>

changed as discussed in slack

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/17#-:-MKLeOdW2sN3sN4d3e-p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
