### PR TITLE
Fix two amcl bugs and do some related minor cleanup along the way

### PR DESCRIPTION
**Pull request by bobhenz-jabil**
This change is [Reviewable](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31)

### CODE REVIEW

**Review by dandedrick — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31)* status: all files reviewed, 1 unresolved discussion (waiting on @bobhenz-jabil)

___
*[`include/amcl/pf/particle_filter.h` line 96 at r3](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31#-O9KV3dg3pyTeE1Sfvv9:-O9KV3dg3pyTeE1SfvvA:b-45kpez) ([raw file](https://github.com/BadgerTechnologies/badger_amcl/blob/c1c9f850574f7b8ef2c60ac23216b5763c5c7edb/include/amcl/pf/particle_filter.h#L96)):*
> ```objc
> public:
>   // Create a new filter
>   ParticleFilter(const Eigen::Vector3d& cluster_size,
> ```

nit: indentation feels a little wonky here

For the added lines this seems to wrap at around 50 characters. If this were just one argument per line that might be stylistically ok but there are then 2 parameters per line. I can sort of appreciate that the parameters are grouped (min/max, fast/slow) but then the final, untouched line is 116 characters long with 2, seemingly, unrelated arguments.

There are a few options that would be cleaner in my opinion:
1. Add random_pose_fn to a new line
2. Wrap to a more standard line length and wrap consistently
3. One parameter per line

Rather than calling the other cases out similarly when this constructor is called via make_shared it follows the same indentation pattern.

**Review by bobhenz-jabil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @dandedrick)

___
*[`include/amcl/pf/particle_filter.h` line 96 at r3](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31#-O9KV3dg3pyTeE1Sfvv9:-O9K_IvI78OmUbA1-ov5:bombmv2) ([raw file](https://github.com/BadgerTechnologies/badger_amcl/blob/c1c9f850574f7b8ef2c60ac23216b5763c5c7edb/include/amcl/pf/particle_filter.h#L96)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

nit: indentation feels a little wonky here

For the added lines this seems to wrap at around 50 characters. If this were just one argument per line that might be stylistically ok but there are then 2 parameters per line. I can sort of appreciate that the parameters are grouped (min/max, fast/slow) but then the final, untouched line is 116 characters long with 2, seemingly, unrelated arguments.

There are a few options that would be cleaner in my opinion:
1. Add random_pose_fn to a new line
2. Wrap to a more standard line length and wrap consistently
3. One parameter per line

Rather than calling the other cases out similarly when this constructor is called via make_shared it follows the same indentation pattern.
</blockquote></details>

Good call. Done.

**Review by dandedrick — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bobhenz-jabil)

**Review by 12tbuchman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 8 of 8 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BadgerTechnologies/badger_amcl/31#-:-OA-SkMQ6-ajSkty7fsa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bobhenz-jabil)

**Pull request merged**
