### PR TITLE
Fix broken badger_amcl test

### PR DESCRIPTION
**Pull request by Ibrahim-Apata**
Replace catkin_add_gtest with add_rostest_gtest so the gtest can run with roscore

Adding test file for badger_amcl

ROS-1011

- - -
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25)

### CODE REVIEW

**Review by leewells7 — CHANGES_REQUESTED** [review]
Needs a better commit message.  Explain WHY you had to make these changes, not just what you did....anyone can see what changed by looking at the diff.  Imagine 5 years from now you want to know what was broken that required this change.

**Review by travisariggs — CHANGES_REQUESTED** [review]
I think this looks ok (except for the commit message), but I'm not approving quite yet.  I'll wait until you fix the jenkins issue that you were having.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25#-:-N97wO1yDgfHnq6OvgJY:bz456ds)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ibrahim-Apata)

**Review by Ibrahim-Apata — COMMENTED** [review]
I spoke with Nicholas and he mentioned that the 2 update fleet stages only happen on a release build, so there are no issues there.

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25#-:-N97xH0GBQtDLVownjUg:bypbx98)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Ibrahim-Apata)

**Review by Ibrahim-Apata — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @travisariggs)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25#-N988d-pCNu-lxuLecds):*
updated the commit message

**Review by leewells7 — APPROVED** [review]

**Review by travisariggs — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25)* status: all files reviewed, 1 unresolved discussion (waiting on @travisariggs)

**Review by travisariggs — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25)* status: all files reviewed, 1 unresolved discussion (waiting on @travisariggs)

**Review by travisariggs — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25)* status: all files reviewed, 1 unresolved discussion (waiting on @Ibrahim-Apata)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/badgertechnologies/badger_amcl/25#-N988d-pCNu-lxuLecds):*
<details><summary><i>Previously, Ibrahim-Apata wrote…</i></summary><blockquote>

updated the commit message
</blockquote></details>

Looks good.

**Pull request merged**
