### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by 12tbuchman**
Various improvements to badger_amcl as specified in [ROS-132](https://badgertech.atlassian.net/browse/ROS-132)

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)

### CODE REVIEW

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 7 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: 7 of 31 files reviewed, 8 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[CMakeLists.txt, line 57 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y5bzW41nMEQEY2Cbu:-M9y5bzW41nMEQEY2Cbv:b1cvm35) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/CMakeLists.txt#L57)):*
> ```CMake
>     src/amcl/pf/pf_kdtree.cpp
>     src/amcl/pf/pdf_gaussian.cpp
>     src/amcl/pf/eig3.cpp
> ```

while changing to eigen, lets replace eig3 with `Eigen::EigenSolver`
___
*[include/amcl/map/map.h, line 53 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y5qrRDZFSxz75PxSW:-M9y5qrRDZFSxz75PxSX:b-g8387w) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/map/map.h#L53)):*
> ```objc
>   // likelihood field
>   double max_distance_to_object_;
>   std::atomic<bool> distances_created_;
> ```

I'm thinking it might be better to call `distances` in this context as `distance_lut`, so maybe `distance_lut_created_`? or something else along those lines, like `distance_table_*` or `distance_cache_*`. Just because `distances_` by itself doesn't convey that the thing created is a relation or lookup-table.
___
*[include/amcl/map/occupancy_map.h, line 71 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6Hk7EFxrcDlQIetH:-M9y6Hk7EFxrcDlQIetI:bm54vcu) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/map/occupancy_map.h#L71)):*
> ```objc
>   virtual void setSize(std::vector<int> size_vec);
>   // Update the distance values
>   virtual void updateDistances(double max_distance_to_object);
> ```

If you follow my idea about adding something to the name distances, this would become `updateDistanceLUT` or `updateDistanceTable` or `updateDistanceCache` or something like that
___
*[include/amcl/map/octomap.h, line 116 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6SVx1pVUe6Ds51JB:-M9y6SVyEpasLPWWtuuy:b-pij123) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/map/octomap.h#L116)):*
> ```objc
> 
> private:
>   void publishDistances();
> ```

here too, I would make this, and any other thing that used to refer to `CSpace` something more like `DistanceLUT` or `DistanceCache`
___
*[include/amcl/node/node.h, line 74 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6ayKB6PUYT5I7VL5:-M9y6ayKB6PUYT5I7VL6:bvzc6di) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L74)):*
> ```objc
>   // Total weight (weights sum to 1)
>   double weight;
>   Eigen::Vector3d mean;
> ```

This is fine. But it would also be fine to say somewhere `using PFVector = Eigen::Vector3d` and fewer lines would have to be touched. I'm fine either way.
___
*[include/amcl/node/node.h, line 85 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6lg-24tQHF9nG1Pw:-M9y6lg-24tQHF9nG1Px:b-32td12) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L85)):*
> ```objc
>   void updateFreeSpaceIndices(std::vector<std::pair<int, int>> fsi);
>   void initOdomIntegrator();
>   bool getOdomPose(const ros::Time& t, Eigen::Vector3d& map_pose);
> ```

if `map_pose` is an output, it should stay a pointer type, per the style guide.
___
*[include/amcl/node/node.h, line 116 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y73bH6P_6ni0LSMAV:-M9y73bI2pS7tjWy6p1H:bkprm1b) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L116)):*
> ```objc
>   void setMsgCovarianceVals(geometry_msgs::PoseWithCovarianceStamped* msg);
>   void transformMsgToTfPose(const geometry_msgs::PoseWithCovarianceStamped& msg, tf2::Transform* pose);
>   void transformPoseToGlobalFrame(const geometry_msgs::PoseWithCovarianceStamped& msg, const tf2::Transform& pose);
> ```

this function seems to have no outputs, I'm confused how it works.
___
*[include/amcl/node/node.h, line 130 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y79Ah7o_6DkvqcVBy:-M9y79Ah7o_6DkvqcVBz:bir28qy) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L130)):*
> ```objc
>   // Odometry integrator
>   void integrateOdom(const nav_msgs::OdometryConstPtr& msg);
>   void calcTfPose(const nav_msgs::OdometryConstPtr& msg, Eigen::Vector3d& pose);
> ```

outputs should stay pointers. there are many other lines where this change was made, so please change all of them.

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 24 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: all files reviewed, 14 unresolved discussions (waiting on @12tbuchman)

___
*[include/amcl/pf/particle_filter.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y8NvE1Ja8g6Rhw19A:-M9y8NvE1Ja8g6Rhw19B:bphqno) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/pf/particle_filter.h#L24)):*
> ```objc
> #define AMCL_PF_PARTICLE_FILTER_H
> 
> #include <Eigen/Dense>
> ```

Eigen is a 3rd party library, so belongs with the next block of includes, not std includes
___
*[include/amcl/pf/particle_filter.h, line 106 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y8WbpEDeC1dA8MEFi:-M9y8WbpEDeC1dA8MEFj:b-gxz65c) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/pf/particle_filter.h#L106)):*
> ```objc
> 
>   // Initialize the filter using a guassian
>   void init(Eigen::Vector3d mean, Eigen::Matrix3d cov);
> ```

it would be more efficient to pass these by const reference. As it is, temporary copies of the matrices will be made. Actually, just looked this up, and for Eigen, this is actually undefined behavior, you must pass by reference:
https://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html
___
*[include/amcl/pf/pf_kdtree.h, line 67 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y9kuL-JM6LTLBY8rj:-M9y9kuL-JM6LTLBY8rk:b-8vx4il) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/pf/pf_kdtree.h#L67)):*
> ```objc
> 
>   // Insert a pose into the tree
>   void insertPose(Eigen::Vector3d pose, double value);
> ```

always pass Eigen vectors by reference, here, and everywhere else
___
*[include/amcl/sensors/planar_scanner.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y9uH44nVTmszsu4Cf:-M9y9uH44nVTmszsu4Cg:b-1gq8dd) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/sensors/planar_scanner.h#L24)):*
> ```objc
> 
> #include <cstddef>
> #include <Eigen/Dense>
> ```

eigen headers go with other third party headers, not standard includes
___
*[include/amcl/sensors/planar_scanner.h, line 92 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9yA3MNBOn-HY5xauSY:-M9yA2U-1TLACN7mIrOQ:bgvj52b) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/sensors/planar_scanner.h#L92)):*
> ```objc
> 
>   // Set the scanner's pose after construction
>   void setPlanarScannerPose(Eigen::Vector3d& scanner_pose);
> ```

This should either be a const reference or a pointer (this was an issue before we missed, but now that you touched this, lets fix it)
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 139 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9yBg1W0GuBg1lNIkp9:-M9yBg1W0GuBg1lNIkpA:b-gic6l5) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/src/amcl/sensors/point_cloud_scanner.cpp#L139)):*
> ```cpp
>   Eigen::Vector3d pose;
> 
>   const double MAX_DISTANCE_TO_OBJECT = map_->getMaxOccDist();
> ```

I don't think all caps is the right style here. It isn't clear that getMaxOccDist always returns the same value for every call. And this isn't an enumeration. I would just name this like a normal variable `max_distance_to_object`

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: 29 of 31 files reviewed, 14 unresolved discussions (waiting on @c-andy-martin)

___
*[CMakeLists.txt, line 57 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y5bzW41nMEQEY2Cbu:-MA27h7y7M0dnw6xUqeZ:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/CMakeLists.txt#L57)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

while changing to eigen, lets replace eig3 with `Eigen::EigenSolver`
</blockquote></details>

Done.
___
*[include/amcl/map/map.h, line 53 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y5qrRDZFSxz75PxSW:-MA2VyAgEH7Ya8L8Wby4:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/map/map.h#L53)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I'm thinking it might be better to call `distances` in this context as `distance_lut`, so maybe `distance_lut_created_`? or something else along those lines, like `distance_table_*` or `distance_cache_*`. Just because `distances_` by itself doesn't convey that the thing created is a relation or lookup-table.
</blockquote></details>

Done.
___
*[include/amcl/map/occupancy_map.h, line 71 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6Hk7EFxrcDlQIetH:-MA2Vyn2AsOUPqoHyywI:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/map/occupancy_map.h#L71)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

If you follow my idea about adding something to the name distances, this would become `updateDistanceLUT` or `updateDistanceTable` or `updateDistanceCache` or something like that
</blockquote></details>

Done.
___
*[include/amcl/map/octomap.h, line 116 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6SVx1pVUe6Ds51JB:-MA2Vzc21t5m5WkrjQor:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/map/octomap.h#L116)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

here too, I would make this, and any other thing that used to refer to `CSpace` something more like `DistanceLUT` or `DistanceCache`
</blockquote></details>

Done.
___
*[include/amcl/node/node.h, line 74 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6ayKB6PUYT5I7VL5:-MA2W1iB1ImvBeUdOGm8:bzh1ehg) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L74)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This is fine. But it would also be fine to say somewhere `using PFVector = Eigen::Vector3d` and fewer lines would have to be touched. I'm fine either way.
</blockquote></details>

Id prefer to not use PFVector so people dont think this is still an internally constructed object. Imho Eigen::Vector3d isnt ugly enough to need a rename.
___
*[include/amcl/node/node.h, line 85 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6lg-24tQHF9nG1Pw:-MA2WM5N7uIfm7lx0K2G:bhg90xu) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L85)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

if `map_pose` is an output, it should stay a pointer type, per the style guide.
</blockquote></details>

Multi dimensional Eigen objects cant be pointed to as they have no accessor methods
___
*[include/amcl/node/node.h, line 116 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y73bH6P_6ni0LSMAV:-MA2WpMf5eZvT4zkEgKe:b-lf5jzn) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L116)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this function seems to have no outputs, I'm confused how it works.
</blockquote></details>

It sets a class member initial_pose_hyp_, there is no output
___
*[include/amcl/node/node.h, line 130 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y79Ah7o_6DkvqcVBy:-MA2Z1jn6gPdUa6mCadC:b-w2ufq0) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L130)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

outputs should stay pointers. there are many other lines where this change was made, so please change all of them.
</blockquote></details>

see previous comment
___
*[include/amcl/pf/particle_filter.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y8NvE1Ja8g6Rhw19A:-MA2lvXI3cazIYc9XCqe:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/pf/particle_filter.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Eigen is a 3rd party library, so belongs with the next block of includes, not std includes
</blockquote></details>

Done.
___
*[include/amcl/pf/particle_filter.h, line 106 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y8WbpEDeC1dA8MEFi:-MA2mVJJ5sb5A79hiqbk:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/pf/particle_filter.h#L106)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

it would be more efficient to pass these by const reference. As it is, temporary copies of the matrices will be made. Actually, just looked this up, and for Eigen, this is actually undefined behavior, you must pass by reference:
https://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html
</blockquote></details>

Done.
___
*[include/amcl/pf/pf_kdtree.h, line 67 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y9kuL-JM6LTLBY8rj:-MA2vH8MAYWHnqm60GSH:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/pf/pf_kdtree.h#L67)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

always pass Eigen vectors by reference, here, and everywhere else
</blockquote></details>

Done.
___
*[include/amcl/sensors/planar_scanner.h, line 24 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y9uH44nVTmszsu4Cf:-MA2vLs50jEWizddNGzL:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/sensors/planar_scanner.h#L24)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

eigen headers go with other third party headers, not standard includes
</blockquote></details>

Done.
___
*[include/amcl/sensors/planar_scanner.h, line 92 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9yA3MNBOn-HY5xauSY:-MA2vPWHEujFYbEaHzWN:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/sensors/planar_scanner.h#L92)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This should either be a const reference or a pointer (this was an issue before we missed, but now that you touched this, lets fix it)
</blockquote></details>

Done.
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 139 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9yBg1W0GuBg1lNIkp9:-MA2xHpv2DNMVbs4k1TA:b-kt7e7o) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/src/amcl/sensors/point_cloud_scanner.cpp#L139)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I don't think all caps is the right style here. It isn't clear that getMaxOccDist always returns the same value for every call. And this isn't an enumeration. I would just name this like a normal variable `max_distance_to_object`
</blockquote></details>

According to the ROS C++ Style Guide constants should be ALL_CAPS
http://wiki.ros.org/CppStyleGuide#Constants

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: 19 of 31 files reviewed, 6 unresolved discussions (waiting on @12tbuchman and @c-andy-martin)

___
*[include/amcl/node/node.h, line 85 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6lg-24tQHF9nG1Pw:-MAXv9ts6LQfbrSCA2Hq:b-28hoep) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L85)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

Multi dimensional Eigen objects cant be pointed to as they have no accessor methods
</blockquote></details>

I do not think this is the case. AFAIK you can always point to something. Please give more details on why this won't work. You should be able to just change to `Eigen::Vector3d* map_pose` and then use `(*map_pose)` in `getOdomPose`wherever you had `map_pose` before and it should work, as `(*map_pose)` should give you exactly this reference.
___
*[include/amcl/node/node.h, line 116 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y73bH6P_6ni0LSMAV:-MAXvVbx2HxqsX9ElKjm:b-99bsmn) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L116)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

It sets a class member initial_pose_hyp_, there is no output
</blockquote></details>

Please add a comment here describing that, as that means the method has side effects a caller may want to know about.
___
*[include/amcl/pf/pdf_gaussian.h, line 38 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-MAXvzTTB5y2dUK64nQO:-MAXvzTTB5y2dUK64nQP:b-isx5fh) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b37d8cb394e8bc9a1a834f0c8452896b9af07132/include/amcl/pf/pdf_gaussian.h#L38)):*
> ```objc
> 
>   // Generate a sample from the the pdf.
>   void sample(Eigen::Vector3d& v);
> ```

BTW, it is OK to return a temporary Eigen::Vector3d, just not pass it in by value. So this change is not strictly necessary. Also, per my previous comment, you should use pointers for all outputs, which I do think is possible.
___
*[src/amcl/pf/pdf_gaussian.cpp, line 23 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-MAXwjeV5tAijTW2ZU4f:-MAXwjeV5tAijTW2ZU4g:b-ekl7wk) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b37d8cb394e8bc9a1a834f0c8452896b9af07132/src/amcl/pf/pdf_gaussian.cpp#L23)):*
> ```cpp
> #include "pf/pdf_gaussian.h"
> 
> #include <Eigen/Eigenvalues>
> ```

this include is a 3rd party, so comes after all standard headers
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 139 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9yBg1W0GuBg1lNIkp9:-MAXwzKm-6oxzGSmCyXc:bxwdwcs) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/src/amcl/sensors/point_cloud_scanner.cpp#L139)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

According to the ROS C++ Style Guide constants should be ALL_CAPS
http://wiki.ros.org/CppStyleGuide#Constants
</blockquote></details>

I think the ROS C++ style guide is referring to things that have `static` storage duration (so are constant at compile time). This is not constant at compile time, I think you are simply creating a convenience alias. It is good to specify such convenience aliases as `const` to keep from inadvertently adding code that modifies them down the road leading to buggy behavior. I would prefer to make it a normal variable name.

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: 12 of 31 files reviewed, 5 unresolved discussions (waiting on @c-andy-martin)

___
*[include/amcl/node/node.h, line 85 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y6lg-24tQHF9nG1Pw:-MAb7bpbC5rqlLgoYQMg:b-vkltja) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L85)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I do not think this is the case. AFAIK you can always point to something. Please give more details on why this won't work. You should be able to just change to `Eigen::Vector3d* map_pose` and then use `(*map_pose)` in `getOdomPose`wherever you had `map_pose` before and it should work, as `(*map_pose)` should give you exactly this reference.
</blockquote></details>

Done. Thanks, I didn't realize that would work.
___
*[include/amcl/node/node.h, line 116 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9y73bH6P_6ni0LSMAV:-MAbi6Gh0kZEHL6HnCpk:bp6qzlg) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/include/amcl/node/node.h#L116)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Please add a comment here describing that, as that means the method has side effects a caller may want to know about.
</blockquote></details>

I renamed the function to better explain what it is doing. I think the comment is not necessary now.
___
*[include/amcl/pf/pdf_gaussian.h, line 38 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-MAXvzTTB5y2dUK64nQO:-MAb7kwP9HG5t9sRhKdb:b-erdumr) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b37d8cb394e8bc9a1a834f0c8452896b9af07132/include/amcl/pf/pdf_gaussian.h#L38)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

BTW, it is OK to return a temporary Eigen::Vector3d, just not pass it in by value. So this change is not strictly necessary. Also, per my previous comment, you should use pointers for all outputs, which I do think is possible.
</blockquote></details>

Yes, I prefer to pass 
___
*[src/amcl/pf/pdf_gaussian.cpp, line 23 at r2](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-MAXwjeV5tAijTW2ZU4f:-MAb81sq0ZYTv0m-1gJX:b-el73l0) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/b37d8cb394e8bc9a1a834f0c8452896b9af07132/src/amcl/pf/pdf_gaussian.cpp#L23)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

this include is a 3rd party, so comes after all standard headers
</blockquote></details>

are you referring to Eigen here or something else?
___
*[src/amcl/sensors/point_cloud_scanner.cpp, line 139 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-M9yBg1W0GuBg1lNIkp9:-MAb9ViCBvB8HsieQVpz:b6htn0a) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/30c22f2d36d0cb6606182b8b57edaaf939c51fac/src/amcl/sensors/point_cloud_scanner.cpp#L139)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I think the ROS C++ style guide is referring to things that have `static` storage duration (so are constant at compile time). This is not constant at compile time, I think you are simply creating a convenience alias. It is good to specify such convenience aliases as `const` to keep from inadvertently adding code that modifies them down the road leading to buggy behavior. I would prefer to make it a normal variable name.
</blockquote></details>

actually looking at the code closer I dont really know why I created this in the first place. the "constant" is created twice and only ever used once. Im just going to get rid of it. But yes, I understand why I would name it like a normal variable if I were to keep it.

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/7#-:-MB0cmsE3POQQvH_5DVA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
