### PR TITLE
Publish initial pose on startup

### PR DESCRIPTION
**Pull request by 12tbuchman**
A boolean parameter can disable publishing the initial pose
on startup if desired.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4)

### CODE REVIEW

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @12tbuchman and @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 478 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4#-M8YHFD276lJu4BgMTgL:-M8YHFD276lJu4BgMTgM:bf5fouz) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/9cd2ba8e1218774af143f6ba0eea034c2a3433c1/src/amcl/node/node.cpp#L478)):*
> ```cpp
>   else
>   {
>     initialPoseReceivedInternal(pose);
> ```

I was thinking if someone sets to not publish the pose, that they were relying on another amcl publishing their pose on startup, and not on the saved pose at tall. I was thinking there would be no else here at all.

**Review by c-andy-martin — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4)* status: all files reviewed, 1 unresolved discussion (waiting on @12tbuchman)

**Review by 12tbuchman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @c-andy-martin)

___
*[src/amcl/node/node.cpp, line 478 at r1](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4#-M8YHFD276lJu4BgMTgL:-M8YP0XS6d5a0L2KrQ0R:b-896fix) ([raw file](https://github.com/badgertechnologies/badger_amcl/blob/9cd2ba8e1218774af143f6ba0eea034c2a3433c1/src/amcl/node/node.cpp#L478)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I was thinking if someone sets to not publish the pose, that they were relying on another amcl publishing their pose on startup, and not on the saved pose at tall. I was thinking there would be no else here at all.
</blockquote></details>

Done.

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/badger_amcl/4#-:-M8YP5HsDC9DJRMouYNj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
